### ISSUE TITLE
Gradle throws a webpack-related error on :frontend:npm_run_start

### ISSUE THREAD

**Issue by srix55** [borysn/spring-boot-angular2#17]
Hi. I followed the setup instructions and I am getting this error.

```
:frontend:build
:frontend:npm_run_start

> spring-boot-angular2@1.0.3 start /home/rocky/DevSpace/espace/spbootng2/frontend
> npm run server:dev


> spring-boot-angular2@1.0.3 server:dev /home/rocky/DevSpace/espace/spbootng2/frontend
> webpack-dev-server --config config/webpack.dev.js --port 3000 -d --progress --profile --watch --content-base src/

/home/rocky/DevSpace/espace/spbootng2/frontend/node_modules/webpack-dev-server/bin/webpack-dev-server.js:376
                throw e;
                ^

TypeError: webpack.validateSchema is not a function
    at new Server (/home/rocky/DevSpace/espace/spbootng2/frontend/node_modules/webpack-dev-server/lib/Server.js:23:33)
    at startDevServer (/home/rocky/DevSpace/espace/spbootng2/frontend/node_modules/webpack-dev-server/bin/webpack-dev-server.js:369:12)
    at processOptions (/home/rocky/DevSpace/espace/spbootng2/frontend/node_modules/webpack-dev-server/bin/webpack-dev-server.js:307:3)
    at Object.<anonymous> (/home/rocky/DevSpace/espace/spbootng2/frontend/node_modules/webpack-dev-server/bin/webpack-dev-server.js:431:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Linux 4.8.0-27-generic
npm ERR! argv "/home/rocky/DevSpace/espace/spbootng2/frontend/node/node-v6.4.0-linux-x64/bin/node" "/home/rocky/DevSpace/espace/spbootng2/frontend/node_modules/.bin/npm" "run" "server:dev"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! spring-boot-angular2@1.0.3 server:dev: `webpack-dev-server --config config/webpack.dev.js --port 3000 -d --progress --profile --watch --content-base src/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the spring-boot-angular2@1.0.3 server:dev script 'webpack-dev-server --config config/webpack.dev.js --port 3000 -d --progress --profile --watch --content-base src/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the spring-boot-angular2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --config config/webpack.dev.js --port 3000 -d --progress --profile --watch --content-base src/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs spring-boot-angular2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls spring-boot-angular2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/rocky/DevSpace/espace/spbootng2/frontend/npm-debug.log

npm ERR! Linux 4.8.0-27-generic
npm ERR! argv "/home/rocky/DevSpace/espace/spbootng2/frontend/node/node-v6.4.0-linux-x64/bin/node" "/home/rocky/DevSpace/espace/spbootng2/frontend/node_modules/npm/bin/npm-cli.js" "run" "start"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! spring-boot-angular2@1.0.3 start: `npm run server:dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the spring-boot-angular2@1.0.3 start script 'npm run server:dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the spring-boot-angular2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run server:dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs spring-boot-angular2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls spring-boot-angular2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/rocky/DevSpace/espace/spbootng2/frontend/npm-debug.log
:frontend:npm_run_start FAILED
```

**Comment by srix55** [comment]
By the way, sorry for this noob question. But, where is the code in spring-boot (or back-end proj) that points to ng2? That is, say this project is in production and you type www.mydomain.com in your browser. So, when the browser contacts mydomain.com (our sboot server), it has to get back the html that's produced by ng2 right? Where is the code that makes the connection between sboot & ng2? How does it work?

**Comment by flaviocordova** [comment]
I'm getting the exact same error.. :(

**Comment by PogoMips** [comment]
This fixed it:
http://stackoverflow.com/questions/40597626/webpack-validateschema-is-not-a-function

**Comment by borysn** [comment]
@srix55 @flaviocordova @PogoMips i'll have to look into this soon, i apologize for my absence guys.

**Comment by borysn** [comment]
@srix55 @flaviocordova @PogoMips alright, there has been an update and new release tagged [v1.1.0](https://github.com/borysn/spring-boot-angular2/releases/tag/1.1.0) going to close out this issue. Let me know if you guys have anymore trouble!
